
remote_theme: jekyll-theme-modernist
##My Week Report


2-Apr-18    

            trailhead 
            debug logs 
            CSC - Case Management : 43397 
            skype call 
            smart box ppt
            
               
3-Apr-18
            
            smart box ppt 
            videos
            build ppt
            R14 trailhead
            
            
4-Apr-18 
        
            created customobject and added fields in R14 
            Validated the task in dev13 Testclasses codecoverage

5-Apr-18    
            
            Youtubevideos 
            POC 
            Apex code
